horizon: 20
grf_max: 200.0
grf_min: 0.0
temperature: 1.0  # 增大温度参数，使权重分布更均匀


weights:
  Q_position: [1, 1, 200]              # z 权重
  Q_velocity: [30, 30, 30]             # 速度权重
  Q_base_angle: [200, 200, 0]          # 增大 roll/pitch 权重
  Q_base_angle_rates: [20, 20, 5]      # 增大角速度权重
  Q_foot_pos: [1, 1, 1]                # 足端位置权重

R:
  R_foot_vel: [0.0001, 0.0001, 0.00001]
  R_foot_force: [0.0001, 0.0001, 0.00001]  # 减小力平滑权重

# Solver / optimizer options
solver:
  use_ddp: false
  use_rti: false
  num_qp_iterations: 12
  as_rti_type: AS-RTI-A  # options: AS-RTI-A, AS-RTI-B, AS-RTI-C, AS-RTI-D
  solver_mode: balance   # options: balance, robust, fast, crazy_speed
  qp_solver_iter_max: 10

  use_nonuniform_discretization: false
  dt_fine_grained: 0.01
  horizon_fine_grained: 4

  use_integrators: true
  alpha_integrator: 0.1
  integrator_clip: [0.5, 0.2, 0.2, 0.0, 0.0, 1.0]